name: Trigger Webhook

on:
  push:
    branches: [ main ]

jobs:
  send-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log push
        run: echo "Push received on main branch!"
